
name: test-scene
run-name: ${{ github.actor }} is test scenes
on:
  - push
jobs:
  get-requirement-and-test-Scenes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install opengl
        run: sudo apt update -y;
             sudo apt install freeglut3-dev -y;
      - name: install ffmpeg
        run: sudo apt install ffmpeg -y;
      - name: install pango
        run: sudo apt install libpango1.0-dev -y;
      - name: install latex
        # run: sudo apt install texlive-full texlive-latex-extra -y;
        run: wget -qO- "https://yihui.org/tinytex/install-bin-unix.sh" | sh
      - name: install numpy version 1.24.3
        run: pip3 install --upgrade pip;
             pip3 install numpy==1.24.3;
      - name: install manimgl
        run: pip3 install manimgl
      - name: install xvfb
        run: sudo apt install xvfb -y

      - name: render Scene TextScene
        run: xvfb-run -a script -c "python3 -m manimlib -w -l myAnimation.py TextScene"
      - name: render Scene SquareScene
        run: xvfb-run -a script -c "python3 -m manimlib -w -l myAnimation.py SquareScene"
      - name: render Scene Tree
        run: xvfb-run -a script -c "python3 -m manimlib -w -l myAnimation.py Tree"
      - name: render Scene TestScene
        run: xvfb-run -a script -c "python3 -m manimlib -w -l myAnimation.py TestScene"
      - name: render Scene TestNumberScene
        run: xvfb-run -a script -c "python3 -m manimlib -w -l myAnimation.py TestNumberScen"

      - name: remove test videos
        run: sudo rm -rf videos/

      - name: render Scene TextScene
        run: xvfb-run -a script -c "python3 -m manimlib -w --uhd myAnimation.py TextScene"
      - name: render Scene SquareScene
        run: xvfb-run -a script -c "python3 -m manimlib -w --uhd myAnimation.py SquareScene"
      - name: render Scene Tree
        run: xvfb-run -a script -c "python3 -m manimlib -w --uhd myAnimation.py Tree"
      - name: render Scene TestScene
        run: xvfb-run -a script -c "python3 -m manimlib -w --uhd myAnimation.py TestScene"
      - name: render Scene TestNumberScene
        run: xvfb-run -a script -c "python3 -m manimlib -w --uhd myAnimation.py TestNumberScen"
      - uses: actions/upload-artifact@v3
        with:
          name: my-vedios
          path: videos/*
