
name: test-scene
run-name: ${{ github.actor }} is test scenes
on:
  - push
jobs:
  run-class-TextScene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg
      # - uses: openrndr/setup-opengl@v1.1
      - run: apt install texlive libpango1.0-dev -y
      - run: pip3 install manimgl
