
name: test-scene
run-name: ${{ github.actor }} is test scenes
on:
  - push
jobs:
  get-requirement-and-test-Scenes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install opengl
        run: sudo apt update -y;
             sudo apt install freeglut3-dev -y;
      - name: install ffmpeg
        run: sudo apt install ffmpeg -y;
      - name: install pango
        run: sudo apt install libpango1.0-dev -y;
      - name: install latex
        run: sudo apt install texlive-full -y;
      - name: install numpy version 1.24.3
        run: pip3 install --upgrade pip;
             pip3 install numpy==1.24.3;
      - name: install manimgl
        run: pip3 install manimgl
      - name: install xvfb
        run: sudo apt install xvfb -y
      # - name: test Scene TextScene
        # run: xvfb-run python3 -m manimlib -w --uhd myAnimation.py TextScene
      - name: test Scene SquareScene
        run: xvfb-run -a python3 -m manimlib -w --uhd myAnimation.py SquareScene
      - name: test Scene Tree
        run: xvfb-run -a python3 -m manimlib -w --uhd myAnimation.py Tree
      - name: test Scene TestScene
        run: xvfb-run -a python3 -m manimlib -w --uhd myAnimation.py TestScene
      - name: test Scene TestNumberScene
        run: xvfb-run -a python3 -m manimlib -w --uhd myAnimation.py TestNumberScen
