
name: test-scene
run-name: ${{ github.actor }} is test scenes
on:
  - push
jobs:
  run-class-TextScene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg
      - name: install requirements and manimgl
        run: sudo apt update ;
             sudo apt install texlive libpango1.0-dev -y ;
             pip3 install manimgl
      - name: test Scene TextScene
        run: python3 -m manimgl -uhd myAnimation.py TextScene -o
